name: ohuac
version: '0.3.0'
category: Devel
author: Sebastian Ertel, Justus Adam
maintainer: sebastian.ertel@gmail.com
copyright: © 2017, 2018, 2020 Sebastian Ertel, Justus Adam
license: OtherLicense
github: sertel/ohuac
extra-source-files:
- README.md
default-extensions:
- OverloadedStrings
- OverloadedLists
- MultiParamTypeClasses
- FunctionalDependencies
- TypeFamilies
- GADTs
- FlexibleContexts
- FlexibleInstances
- TypeSynonymInstances
- LambdaCase
- TupleSections
- BangPatterns
- ExplicitForAll
- ScopedTypeVariables
- DefaultSignatures
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable
- DeriveGeneric
- PatternSynonyms
- NoImplicitPrelude
- TypeApplications
- NamedFieldPuns
- RecordWildCards
- RankNTypes
- ViewPatterns
- NoImplicitPrelude
- StandaloneDeriving
dependencies:
- base
- ohua-core >= 0.3.0
- bytestring
- aeson
- filepath
- directory
- template-haskell
- unordered-containers
- lens
- monad-control
library:
  source-dirs: src
  dependencies:
  - async
  - mtl
  - text
  - recursion-schemes
  - lifted-async
  - containers
  - casing
  - parser-commons
  - alang-go-parser
executables:
  ohuac:
    main: Main.hs
    source-dirs: app
    dependencies:
    - ohuac
    - optparse-applicative
    - time
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints

tests:
  ohua-standalone-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
