name:                ohua-frontend
version:             0.1.0.0
github:              "sertel/ohua-frontend"
license:             BSD3
author:              "Sebastian Ertel"
maintainer:          "sebastian.ertel@gmail.com"
copyright:           "2020 Sebastian Ertel"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/sertel/ohua-frontend#readme>

dependencies:
- base >= 4.8 && < 5
- text
- containers
- ohuac-commons
- extra
- language-rust
- lens
- recursion-schemes
- unordered-containers
- filepath
- directory
- bytestring

default-extensions:
- OverloadedStrings
- OverloadedLists
- MultiParamTypeClasses
- FunctionalDependencies
- TypeFamilies
- GADTs
- FlexibleContexts
- FlexibleInstances
- TypeSynonymInstances
- LambdaCase
- TupleSections
- BangPatterns
- ExplicitForAll
- ScopedTypeVariables
- DefaultSignatures
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable
- DeriveGeneric
- PatternSynonyms
- NamedFieldPuns
- RecordWildCards
- ConstraintKinds
- StandaloneDeriving
- NoImplicitPrelude
- RankNTypes
- ViewPatterns

library:
  source-dirs: src

tests:
  ohua-frontend-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - ohua-frontend
    - hspec
