name: ohuac
version: '0.3.0'
category: Devel
author: Sebastian Ertel
maintainer: sebastian.ertel@gmail.com
copyright: © 2020 Sebastian Ertel
license: OtherLicense
github: sertel/ohuac


extra-source-files:
- README.md


description:         Please see the README on GitHub at <https://github.com/ohua-lang/condrust#readme>


ghc-options:
- -Wall
- -Werror=inaccessible-code
- -Werror=incomplete-patterns


default-extensions:
- OverloadedStrings
- MultiParamTypeClasses
- FunctionalDependencies
- TypeFamilies
- GADTs
- FlexibleContexts
- FlexibleInstances
- TypeSynonymInstances
- LambdaCase
- TupleSections
- BangPatterns
- ExplicitForAll
- ScopedTypeVariables
- DefaultSignatures
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable
- DeriveGeneric
- PatternSynonyms
- NoImplicitPrelude
- TypeApplications
- NamedFieldPuns
- RecordWildCards
- ConstraintKinds
- StandaloneDeriving
- RankNTypes
- ViewPatterns
- DataKinds

dependencies:
- base
- ohuac-integrations


- bytestring
- filepath
- directory

- unordered-containers
- lens
- extra

 # additional dependencies from commons
- universum >= 1.0 # on version 1.6.1
- generic-lens >= 1.0.0.2
- data-default-class
- monad-control
- mtl
- monad-logger
- safe-exceptions
- template-haskell
- th-lift-instances
- th-lift
- text
- fast-logger
- singletons
- prettyprinter

 # additional dependencies from backend
- containers
- ordered-containers
- yaml
- recursion-schemes

library:
  source-dirs: src
  dependencies:
  - async
  - mtl
  - text
  - recursion-schemes
  - lifted-async
  - containers
  - casing
  - yaml
  
  # see ghcide bug: https://github.com/digital-asset/ghcide/issues/49
  # for now comment those out on commit
  # - hspec
  # - raw-strings-qq

executables:
  ohuac:
    main: Main.hs
    source-dirs: app
    dependencies:
    - ohuac
    - optparse-applicative
    - time
    - template-haskell
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints

tests:
  ohua-standalone-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - base
    - ohuac
    - yaml
    - hspec
    - raw-strings-qq
    - temporary
    - language-python
    - language-rust
    - template-haskell
    - prettyprinter
    - text
    - bytestring
