name: ohuac
version: '0.3.0'
category: Devel
author: Sebastian Ertel
maintainer: sebastian.ertel@gmail.com
copyright: © 2020 Sebastian Ertel
license: OtherLicense
github: sertel/ohuac
extra-source-files:
- README.md
default-extensions:
- OverloadedStrings
- OverloadedLists
- MultiParamTypeClasses
- FunctionalDependencies
- TypeFamilies
- GADTs
- FlexibleContexts
- FlexibleInstances
- TypeSynonymInstances
- LambdaCase
- TupleSections
- BangPatterns
- ExplicitForAll
- ScopedTypeVariables
- DefaultSignatures
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable
- DeriveGeneric
- PatternSynonyms
- NoImplicitPrelude
- TypeApplications
- NamedFieldPuns
- RecordWildCards
- RankNTypes
- ViewPatterns
- NoImplicitPrelude
- StandaloneDeriving
- DataKinds

dependencies:
- base
- ohuac-commons
- ohua-frontend
- ohua-core >= 0.3.0
- ohua-backend
- ohuac-integrations
- bytestring
- filepath
- directory
- unordered-containers
- lens
- extra

library:
  source-dirs: src
  dependencies:
  - async
  - mtl
  - text
  - recursion-schemes
  - lifted-async
  - containers
  - casing
  - yaml
  
  # see ghcide bug: https://github.com/digital-asset/ghcide/issues/49
  # for now comment those out on commit
  # - hspec
  # - raw-strings-qq

executables:
  ohuac:
    main: Main.hs
    source-dirs: app
    dependencies:
    - ohuac
    - optparse-applicative
    - time
    - template-haskell
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints

tests:
  ohua-standalone-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - ohuac
    - yaml
    - hspec
    - raw-strings-qq
    - temporary
    - language-rust
    - prettyprinter
    - text
    - bytestring
