resolver: lts-14.22 # ghc-8.6.5

packages:
- .

extra-deps:
  # - language-rust-0.2.0.27@sha256:d96ec43076689ca8932a78b523b668de30a6b1f3b4fb6386017732028e591da7,6835
  - git: https://github.com/harpocrates/language-rust
    commit: 9d509c450d009cc99f1180b3f2f30247dfb1cfce
  # - git: https://github.com/sertel/ohuac-commons
  # commit: ???
  - ../ohuac-commons # debugging