resolver: lts-21.4 #lts-16.23 # lts-14.22 # ghc-8.6.5
extra-deps:
  # - git: https://github.com/sertel/ohuac-commons
  # commit: ???
  - ../ohuac-commons # debugging
flags:
  ohua-core:
    debug: true
ghc-options:
  "$locals": -DDEBUG=1
nix:
  enable: true
  packages: [zlib.dev, zlib.out]
extra-package-dbs: []
packages:
- ./core
#- ./test-tools
#- ./tests

