resolver:  lts-16.23 # lts-14.22 # ghc-8.6.5

packages:
- .

extra-deps:
  #- git: https://github.com/sertel/ohuac-commons
  #  commit: ???
  - ../ohuac-commons # debugging
  #- git: https://github.com/sertel/ohua-frontend
  #  commit: ???
  - ../ohua-frontend # debugging
  # - git: https://github.com/sertel/ohua-core
  #   commit: 9600303eef3acf0e42aa1957f98654042fef58ba
  #   subdirs: [core]
  - ../ohua-core/core # debugging
  #- git: https://github.com/sertel/ohua-backend
  #  commit: ???
  - ../ohua-backend # debugging
  #- git: https://github.com/sertel/ohuac-integrations
  #  commit: ???
  - ../ohuac-integrations # debugging

  # for reproducibility reasons, stack requires me to specify this again here.
  # TODO Is there a way that I can tell stack that it should use the version specified in ohuac-integrations?
  - github: harpocrates/language-rust
    commit: 9d509c450d009cc99f1180b3f2f30247dfb1cfce # master
    #commit: 625eb5ee26f46045effcbc8f924598d26ee25c2a # branch for rust 1.39


flags:
  ohua-core:
    debug: true

nix:
  enable: true
  packages: [zlib.dev, zlib.out]

extra-package-dbs: []
