resolver: lts-12.10
packages:
- .

extra-deps: 
  - git: https://github.com/ohua-dev/ohua-core
    commit: d499652f022be7dc5e1fc58df70949313cacebda
    subdirs: [core]
  - git: https://github.com/sertel/alang-go-parser
    commit: 0eb0a6e3c64759ed0e1d8fb8124ac09060959348
  - git: https://github.com/sertel/parser-commons
    commit: e0b6a789ec67702ed63aa781ac640873101aba07

flags:
  ohua-core:
    debug: true
extra-package-dbs: []
