resolver: lts-14.22 # ghc-8.6.5
extra-deps:
  # - git: https://github.com/sertel/ohuac-commons
  # commit: ???
  - ../ohuac-commons # debugging
flags:
  ohua-core:
    debug: true
extra-package-dbs: []
packages:
- ./core
- ./test-tools
- ./tests

