resolver: lts-14.22 # ghc-8.6.5
flags:
  ohua-core:
    debug: true
extra-package-dbs: []
packages:
- ./core
- ./test-tools
- ./tests

extra-deps: 
  - git: https://github.com/sertel/alang-ml-parser
    commit:  55afe8e5de0417f6be00ff87586a8436c94529c1

