resolver: lts-14.22 # ghc-8.6.5
packages:
- .

extra-deps: 
  - git: https://github.com/sertel/ohua-core
    commit: 118404f6e7d57f5f602648abfcd7a2b81dced525
    subdirs: [core]
  - git: https://github.com/sertel/alang-go-parser
    commit: dbbc66f9b816a99b55ab85d13bda491ae0c2c307
  - git: https://github.com/sertel/parser-commons
    commit: 477e53298d3160712f053345152d65e424ea77e6

flags:
  ohua-core:
    debug: true
extra-package-dbs: []
