resolver: lts-12.10
packages:
- .

extra-deps: 
  - git: https://github.com/ohua-dev/ohua-core
    commit: d499652f022be7dc5e1fc58df70949313cacebda
    subdirs: [core]
  - git: https://github.com/sertel/alang-go-parser
    commit: b4286cef82a7290a5767f18572bdb6673812e6ad

flags:
  ohua-core:
    debug: true
extra-package-dbs: []
