resolver: lts-14.22 # ghc-8.6.5
flags:
  ohua-core:
    debug: true
extra-package-dbs: []
packages:
- ./core
- ./test-tools
- ./tests

# FIXME alang-ml-parser also depends on ohua-core. this dependency needs to go away!
#       one solution would be to have a separate repo for the tests.
extra-deps: 
  - git: https://github.com/sertel/alang-ml-parser
    commit:  c8d2d5ebccc4a81d7ca64627721fe43fd5c0a695

