resolver: lts-21.4 #lts-16.23 # lts-14.22 # ghc-8.6.5

packages:
- .

extra-deps:
  # - git: https://github.com/sertel/ohuac-commons
  # commit: ???
  - ../ohuac-commons # debugging
  - ordered-containers-0.2.2