resolver: lts-14.22 # ghc-8.6.5
packages:
- .

extra-deps: 
  - git: https://github.com/sertel/ohua-core
    commit: 9600303eef3acf0e42aa1957f98654042fef58ba
    subdirs: [core]
  # - ../ohua-core/core # debugging
  - git: https://github.com/sertel/alang-go-parser
    commit: 938dae6929c27069f3065e32e0ac373db5e84e0a
  - git: https://github.com/sertel/parser-commons
    commit: 477e53298d3160712f053345152d65e424ea77e6

flags:
  ohua-core:
    debug: true
extra-package-dbs: []
