resolver: lts-21.4 #lts-16.23 # lts-14.22 # ghc-8.6.5

packages:
- .

extra-deps:
  #- git: https://github.com/sertel/ohuac-commons
  #  commit: ???
  - ../ohuac-commons # debugging
  #- git: https://github.com/sertel/ohua-frontend
  #  commit: ???
  - ../ohua-frontend # debugging
  #- git: https://github.com/sertel/ohua-backend
  #  commit: ???
  - ../ohua-backend # debugging
  - ../ohua-core/core

  - github: GaloisInc/language-rust
    #commit: 9d509c450d009cc99f1180b3f2f30247dfb1cfce # master
    commit: 6cb5c28 # branch for rust 1.39

  - language-python-0.5.8@sha256:527615d39d4240ca45ed8cb7fe44cbcb28a07732cc98dff0380d04de8b55f59d,2473
  # - tomland-1.3.3.2
  #- megaparsec-9.2.2
  #- validation-selective-0.1.0.2

extra-package-dbs: []
