resolver:  lts-21.4 # lts-14.22 # ghc-8.6.5

packages:
- .

extra-deps:
  #- git: https://github.com/sertel/ohua-frontend
  #  commit: ???
  - ../ohua-frontend # debugging
  #- git: https://github.com/sertel/ohua-backend
  #  commit: ???
  - ../ohua-backend # debugging
  #- git: https://github.com/sertel/ohuac-integrations
  #  commit: ???
  - ../ohuac-integrations # debugging

  # for reproducibility reasons, stack requires me to specify this again here.
  # TODO Is there a way that I can tell stack that it should use the version specified in ohuac-integrations?
  - github: Pagolin/language-rust #GaloisInc/language-rust
    #commit: 9d509c450d009cc99f1180b3f2f30247dfb1cfce # master
    commit: 131b7d1 # branch for rust 1.39

  - language-python-0.5.8@sha256:527615d39d4240ca45ed8cb7fe44cbcb28a07732cc98dff0380d04de8b55f59d,2473

flags:
  ohua-core:
    debug: true

nix:
  enable: true
  packages: [zlib.dev, zlib.out, cargo, python3Minimal]

extra-package-dbs: []
