on: 
  push: 
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout condrust
        uses: actions/checkout@v3
        with:
          repository: 'ohua-lang/condrust'
          # token: ${{ secrets.PULL_TOKEN }}
          fetch-depth: 0
          path: 'condrust'
      - name: Get current branch
        id: branch-name
        uses: tj-actions/branch-names@v5
      - name: Check out the branch in question
        run: |
          for dir in */
          do
            cd $dir
            if git rev-parse --quiet --verify origin/${{ steps.branch-name.outputs.current_branch }} > /dev/null; then
              git checkout ${{ steps.branch-name.outputs.current_branch }}
              echo "$dir checked out ${{ steps.branch-name.outputs.current_branch }}"
            else
              echo "$dir has no branch ${{ steps.branch-name.outputs.current_branch }}"
            fi
            cd ..
          done
        shell: bash

      - name: Setup Haskell
        uses: haskell/actions/setup@v1
      # set up nix
      - name: Install nix
        uses: cachix/install-nix-action@v18
        with:
          #install_url: https://github.com/NixOS/nixpkgs/archive/b6966d911da89e5a7301aaef8b4f0a44c77e103c.tar.gz
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Get nixpkgs hash
        id: nixpkgs-hash
        run: |
          echo "name=hash::$(nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version')" >> $GITHUB_OUTPUT
        shell: bash
      
      - name: Build condrust
        run: |
          cd condrust
          nix-shell --run "stack build"
      - name: Run tests
        run: |
          cd condrust
          nix-shell --run "stack test"
